"""add_stripe_customer_id_to_tenants

Revision ID: 156cc59acf36
Revises: 8df03f60eb58
Create Date: 2026-07-05 19:26:16.694440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156cc59acf36'
down_revision: Union[str, None] = '8df03f60eb58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leads_tenant_last_interaction', table_name='leads')
    op.drop_index('ix_leads_tenant_status_tier', table_name='leads')
    op.add_column('tenants', sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'stripe_customer_id')
    op.create_index('ix_leads_tenant_status_tier', 'leads', ['tenant_id', 'status', 'tier'], unique=False)
    op.create_index('ix_leads_tenant_last_interaction', 'leads', ['tenant_id', 'last_interaction'], unique=False)
    # ### end Alembic commands ###
