"""add_subscription_fields_to_tenants

Revision ID: 6854d88a1a66
Revises: 156cc59acf36
Create Date: 2026-07-05 20:50:50.650487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6854d88a1a66'
down_revision: Union[str, None] = '156cc59acf36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('pending_plan', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('pending_plan_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'pending_plan_date')
    op.drop_column('tenants', 'pending_plan')
    op.drop_column('tenants', 'stripe_subscription_id')
    # ### end Alembic commands ###
